export const SHOPPING_LIST = [
  {
    id: 1,
    name: "화이트 자켓",
    category: "상의",
    value: 23000,
    imgUrl: "../assets/contents/상의/img1.png",
  },
  {
    id: 2,
    name: "맨투맨",
    category: "상의",
    value: 18000,
    imgUrl: "../assets/contents/상의/img2.png",
  },
  {
    id: 3,
    name: "바람막이",
    category: "상의",
    value: 22000,
    imgUrl: "../assets/contents/상의/img3.png",
  },
  {
    id: 4,
    name: "셔츠",
    category: "상의",
    value: 20000,
    imgUrl: "../assets/contents/상의/img4.png",
  },
  {
    id: 5,
    name: "핀턱 코튼 와이드 팬츠",
    category: "하의",
    value: 50000,
    imgUrl: "../assets/contents/하의/img1.png",
  },
  {
    id: 6,
    name: "크로스 트레이닝 팬츠",
    category: "하의",
    value: 42000,
    imgUrl: "../assets/contents/하의/img2.png",
  },
  {
    id: 7,
    name: "블랙 와이드 팬츠",
    category: "하의",
    value: 39000,
    imgUrl: "../assets/contents/하의/img3.png",
  },
  {
    id: 8,
    name: "더비 슈즈",
    category: "신발",
    value: 104000,
    imgUrl: "../assets/contents/신발/img1.png",
  },
  {
    id: 9,
    name: "패디드 슬리퍼",
    category: "신발",
    value: 35000,
    imgUrl: "../assets/contents/신발/img2.png",
  },
  {
    id: 10,
    name: "플립 플롭",
    category: "신발",
    value: 22000,
    imgUrl: "../assets/contents/신발/img3.png",
  },
  {
    id: 11,
    name: "어그 부츠",
    category: "신발",
    value: 60000,
    imgUrl: "../assets/contents/신발/img4.png",
  },
];
